apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: ghcr.io/andresurbanog/guestbook-frontend-arm64:latest
        ports:
        - containerPort: 80
        env:
        - name: REDIS_MASTER_SERVICE_HOST
          value: redis-leader
        - name: REDIS_SLAVE_SERVICE_HOST
          value: redis-follower
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: guestbook
    tier: frontend
