apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-follower
spec:
  selector:
    matchLabels:
      app: redis
      role: follower
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: follower
    spec:
      containers:
      - name: follower
        image: redis:7.2-alpine
        ports:
        - containerPort: 6379
        env:
        - name: GET_HOSTS_FROM
          value: dns
---
apiVersion: v1
kind: Service
metadata:
  name: redis-follower
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: follower
