apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-leader
spec:
  selector:
    matchLabels:
      app: redis
      role: leader
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: leader
    spec:
      containers:
      - name: leader
        image: docker.io/redis:6.0.5
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-leader
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: leader
